### PR TITLE
New release process using docker, circleci and a centralized building tool

### LINKED ISSUE #75: Use new build process
This should use the new build process. This will close #66 and #43. Not urgent though.

/cc @sdurrheimer

### PR DESCRIPTION
**Pull request by sdurrheimer**
Fixes #75 #66 #43

@discordianfish

### CODE REVIEW

**Comment by beorn7** [comment]
Fantastic. Thanks for all of this.

:+1: but let's give @discordianfish a chance to have a look, too.

**Comment by discordianfish** [comment]
LGTM, thanks!

**Comment by discordianfish** [comment]
@sdurrheimer Can you merge this now? Because you still have it marked as [WIP].

**Comment by sdurrheimer** [comment]
I must prepare the CircleCI job, I will do it this evening. I will merge it just after a test build.

**Pull request merged**
