### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by beorn7**
Also, add a go version line, as this tends to be added automatically
by tools, but then it adds the Go version currently used, while
Pushgateway should just build fine with older Go versions. (Specifying
anything earlier than Go1.11 doesn't make sense, though, as Go modules
weren't supported previously.)

Signed-off-by: beorn7 <beorn@grafana.com>

### CODE REVIEW

**Comment by beorn7** [comment]
We still need to update golang-builder to Go1.13.

**Comment by simonpasquier** [comment]
golangci-lint is broken with Go 1.13 (see https://github.com/golangci/golangci-lint/issues/652 and https://github.com/golangci/golangci-lint/issues/659). We also need https://github.com/prometheus/golang-builder/pull/76 which I haven't merged yet because of that same issue.

**Comment by beorn7** [comment]
That explains it. Thanks. So we'll have more things waiting for getting unblocked.

**Comment by beorn7** [comment]
Also needed to update the vendored files.

**Comment by beorn7** [comment]
@simonpasquier build is green now.

**Pull request merged**
