### PR TITLE
Update dependencies and Go

### PR DESCRIPTION
**Pull request by beorn7**
dependabot choked on the prometheus/prometheus update because of the `toolchain` directive in go.mod.
So I thought, let's update Go and all the dependencies properly.
I might cut a release with the now Go version soon, to pacify "security" scanners.
(Maybe I'll even do a bootstrap update for the same reason, but first I have to get this here done.)

### CODE REVIEW

**Comment by beorn7** [comment]
Hmm, it looks CircleCI doesn't have go1.23 yet…

**Comment by SuperQ** [comment]
No, we're still waiting on `cimg/go:1.23`. :crying_cat_face:

**Comment by SuperQ** [comment]
Now that Go 1.23.1 is out, they should be able to fix their release.

**Comment by beorn7** [comment]
We'll just wait a bit. I don't think this is very urgent.

**Comment by beorn7** [comment]
Now it works! :tada:

**Review by SuperQ — APPROVED** [review]

**Pull request merged**
