### PR TITLE
Update template.html

### PR DESCRIPTION
**Pull request by nhathoangvy**
Add css for badge info get error

### CODE REVIEW

**Comment by beorn7** [comment]
Thanks for your contribution. Could you sign the DCO? See https://github.com/prometheus/pushgateway/pull/397/checks?check_run_id=2244593779

Also, could you explain the change? Bonus points for screenshot before/after.

**Comment by nhathoangvy** [comment]
Hi @beorn7 !
I want to separate API success and fail UI .
So just that .

**Comment by beorn7** [comment]
Those badges don't always look as expected. Could you attach a screenshot before and after?

**Comment by nhathoangvy** [comment]
Screen Shot 2021-04-09 at 08 27 29
@beorn7 like this

**Comment by beorn7** [comment]
Thank you very much. Only now I understand what this is about. (I should have seen that earlier, but the screenshot was helpful indeed.)

So, the current behavior treats the `instance` and the `job` label special because they are actually special in a technical sense (the `job` label is mandatory, and the `instance` label is auto-set to `""` if not specified explicitly). However, an `error` label or a `result` label and their label values are just conventions. For the PGW and for Prometheus, they aren't special at all. There isn't even any general practice or convention in the Prometheus ecosystem to have any of those labels, not to speak about specific values. Therefore, I don't think we should color the labels here in the PGW UI solely based on a weak heuristics like "`failed` in the label value" or "the label name is `error`".

**Comment by beorn7** [comment]
Assuming the lack of follow-up means my line of argument above is sound, I'll close thise.

**Pull request closed without merging**
