### PR TITLE
Updates to Makefiles

### PR DESCRIPTION
**Pull request by beorn7**
@apghero does this perhaps help you with #240 ?

### CODE REVIEW

**Comment by beorn7** [comment]
OK, so that's not enough as the `go run` called from within `go generate` is misbehaving if a `GOPATH` is set.

**Comment by beorn7** [comment]
Last commit added here should really fix #240. @simonpasquier I hope that makes sense. Not sure why we needed the more complicated path calculation in the first place. Perhaps you know something about it.

**Comment by apghero** [comment]
@beorn7 this works without the symlink in my GOPATH. :+1:

**Comment by beorn7** [comment]
OK, merging now. @simonpasquier please let me know if you have any concerns.

**Comment by simonpasquier** [comment]
@beorn7 all good for me!

> Not sure why we needed the more complicated path calculation in the first place. Perhaps you know something about it.

IIRC it was taken from the https://github.com/shurcooL/vfsgen examples but indeed we simplified it the same way in [prometheus/prometheus](https://github.com/prometheus/prometheus/commit/d89c01b0658465523cca1986a584e2598488e315).

**Pull request merged**
