### PR TITLE
Add image build for s390x architecture

### PR DESCRIPTION
**Pull request by modassarrana89**
Updated Makefile for adding s390x architecture 
Updated .dockerignore  file for s390x

### CODE REVIEW

**Comment by beorn7** [comment]
I guess this should just work. It's similar to https://github.com/prometheus/prometheus/pull/6486 .

@simonpasquier you reviewed that PR back in the days. Do you see any concerns here?

I'll merge for now, but wait a bit before cutting a release.

**Review by beorn7 — APPROVED** [review]

**Comment by beorn7** [comment]
For posteriority:

For the push to quay.io to work, I had to manually create the repository https://quay.io/repository/prometheus/pushgateway-linux-s390x

**Comment by modassarrana89** [comment]
Pushgateway tar file is already s390x & same is being used in Quay . So this change was Just to build the image for pushgateway for s390x . This build is not for Quay

**Comment by modassarrana89** [comment]
Thanks for the update . I can see s390x image for master release . Is there any plan to keep it as part of other release ex latest , etc

**Comment by beorn7** [comment]
I will cut a new release in the next days, which will get an image than for an official release.

I do not plan to add images to older releases. There haven't been any invasive changes in the PGW for years, so I don't anticipate substantial need to run older versions instead of the current one.

**Pull request merged**
